name: contacts_app
description: A Clean Architecture Flutter project

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5
  dio: ^5.3.2
  get_it: ^8.2.0
  shared_preferences: ^2.5.3
  cached_network_image: ^3.3.0
  image_picker: ^1.0.4
  intl: ^0.20.2
  logger: ^2.0.2
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  mockito: ^5.4.2
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true